### ISSUE TITLE
running builds from go >=1.15 results in errors

### ISSUE THREAD

**Issue by debugloop** [letsencrypt/unbound_exporter#33]
Specifically, this error is thrown: `level=error ts=2021-12-17T08:23:05.192Z caller=unbound_exporter.go:461 Failedtoscrapesocket:="x509: certificate relies on legacy Common Name field, use SANs instead"`

This happens when unbound is left using its own certificate without giving it a proper, non-selfsigned one.
This appears to be intended behaviour from 1.15 onwards (https://go.dev/doc/go1.15#commonname). While these release notes describe a fix using the GODEBUG variable, this seems to be removed as of go 1.17.

**Comment by jprenken** [comment]
Duplicates #20
