### ISSUE TITLE
Unbound Control certificate Issue

### ISSUE THREAD

**Issue by ahsifer** [letsencrypt/unbound_exporter#41]
After installing the exporter and running the binary I have faced the following issue
level=error ts=2022-07-03T05:42:51.829Z caller=unbound_exporter.go:461 Failedtoscrapesocket:="x509: certificate relies on legacy Common Name field, use SANs instead"

**Comment by jprenken** [comment]
Go now requires that server certificates use Subject Alternative Name (SAN) extensions. So, unbound_exporter will encounter this error if it's built with Go 1.15+ and tries to connect to a copy of Unbound that's using an older certificate. ([Unbound issue #316](https://github.com/NLnetLabs/unbound/issues/316).) The `unbound-control-setup.sh` script from Unbound 1.13 or newer can help you generate a newer certificate. I hope this helps!

**Comment by ahsifer** [comment]
Thank you @jprenken this worked for me.

**Comment by jprenken** [comment]
Great! Note to self, this was an instance of #20
