### ISSUE TITLE
dashboards grafanna show NA

### ISSUE THREAD

**Issue by liang-hiwin** [letsencrypt/unbound_exporter#46]
```
run command

root@linux:~/build# curl 127.0.0.1:9167/metrics | grep '^unbound_up'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17143    0 17143    0     0  1674k      0 --:--:-- --:--:-- --:--:-- 1674k
unbound_up 1

```

![4`0WV(5XWYXA7D K$Q@M (J](https://user-images.githubusercontent.com/17548936/192321651-d0565b20-0b38-4e6b-b05c-7433987c0fea.png)

**Comment by jsha** [comment]
- If you query your Prometheus instance for `unbound_up`, does it show the metric?
- Is your Grafana successfully querying your Prometheus instance? One way to test: if you use the "Explore" feature on Grafana, does it show any metrics?

**Comment by liang-hiwin** [comment]
> * If you query your Prometheus instance for `unbound_up`, does it show the metric?
> * Is your Grafana successfully querying your Prometheus instance? One way to test: if you use the "Explore" feature on Grafana, does it show any metrics?

Sorry to solve it, the reason is the problem of prometheus configuration.

**Comment by liang-hiwin** [comment]
Threads and cachedb unbound_exporter currently does not support later update can increase support?

**Comment by jsha** [comment]
Threads are supported. For instance the statistic that is reported by Unbound as `thread0.num.recursivereplies=48` is reported in Prometheus as `recursive_replies_total{thread="0"}`.

https://github.com/letsencrypt/unbound_exporter/blob/main/unbound_exporter.go#L210-L215

**Comment by liang-hiwin** [comment]
> Threads are supported. For instance the statistic that is reported by Unbound as `thread0.num.recursivereplies=48` is reported in Prometheus as `recursive_replies_total{thread="0"}`.
> 
> https://github.com/letsencrypt/unbound_exporter/blob/main/unbound_exporter.go#L210-L215

I mean to display the value of the "num-threads" parameter of the unbound configuration below
```
num-threads: 4
msg-cache-slabs: 8
rrset-cache-slabs: 8
key-cache-slabs: 8
infra-cache-slabs: 8
```

**Comment by jsha** [comment]
I think that parameter is not exported by unbound-stats. You can file an upstream issue with unbound to export it. You may also be able to make a Prometheus query that counts the number of distinct values for the `thread=` label in, e.g. `recursive_replies_total`. I'm afraid I don't know how to write such a query.
