### ISSUE TITLE
openssl error trying to run on ubuntu 22.04 jammy

### ISSUE THREAD

**Issue by furlongm** [letsencrypt/unbound_exporter#55]
Ubuntu 22.04 jammy no longer has openssl1 so the current release fails to run there:

```
# /usr/local/sbin/unbound-telemetry
/usr/local/sbin/unbound-telemetry: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

```
# dpkg -L libssl3 | grep libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.3
```

**Comment by pgporada** [comment]
@furlongm I think you might be trying to run [this code](https://github.com/svartalf/unbound-telemetry) instead?

**Comment by furlongm** [comment]
Yep - sorry for the noise! Looks like that one is deprecated so will look at switching here.
